USE [master]
GO

/****** Object:  Database [Aula]    Script Date: 07/05/2019 03:39:29 ******/
CREATE DATABASE [Aula] ON  PRIMARY 
( NAME = N'Aula', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\Aula.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Aula_log', FILENAME = N'c:\Program Files\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\Aula_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [Aula] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Aula].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Aula] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Aula] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Aula] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Aula] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Aula] SET ARITHABORT OFF 
GO

ALTER DATABASE [Aula] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Aula] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [Aula] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Aula] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Aula] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Aula] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Aula] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Aula] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Aula] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Aula] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Aula] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Aula] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Aula] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Aula] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Aula] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Aula] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Aula] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Aula] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Aula] SET  READ_WRITE 
GO

ALTER DATABASE [Aula] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Aula] SET  MULTI_USER 
GO

ALTER DATABASE [Aula] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Aula] SET DB_CHAINING OFF 
GO

